# Generated by Django 5.0.6 on 2024-07-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="posted_as",
            field=models.CharField(
                choices=[("Новости", "Новости"), ("Событие", "Событие")], max_length=10
            ),
        ),
    ]
