# Generated by Django 5.0.6 on 2024-07-04 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_alter_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip",
                null=True,
                upload_to="course_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7zip",
                        ]
                    )
                ],
            ),
        ),
    ]
