# Generated by Django 5.0.6 on 2024-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_uploadvideo_file"),
        ("quiz", "0004_alter_question_figure_alter_quiz_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadvideo",
            old_name="timestamp",
            new_name="upload_time",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="slug",
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="quizzes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="videos", to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
