# Generated by Django 5.0.6 on 2024-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_rename_timestamp_uploadvideo_upload_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadvideo",
            old_name="upload_time",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="quizzes",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
