# Generated by Django 5.0.6 on 2024-07-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_rename_upload_time_uploadvideo_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadvideo",
            name="file",
        ),
    ]
