# Generated by Django 5.0.6 on 2024-07-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_alter_uploadvideo_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_elective",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                default=models.SlugField(blank=True, unique=True),
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="credit",
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Bachelor", "Bachelor Degree"), ("Master", "Master Degree")],
                default="Bachelor",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                default="First",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (4, "5"), (4, "6")],
                default=2,
            ),
        ),
    ]
