# Generated by Django 5.0.6 on 2024-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_remove_course_is_elective_alter_course_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                default="92fca0", max_length=200, null=True, unique=True
            ),
        ),
    ]
