# Generated by Django 5.0.6 on 2024-07-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_alter_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                default=models.SlugField(blank=True, unique=True),
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
