# Generated by Django 5.0.6 on 2024-07-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_alter_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_elective",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                default="Second",
                max_length=200,
            ),
        ),
    ]
