# Generated by Django 5.0.6 on 2024-07-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_course_is_elective_alter_course_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-id"]},
        ),
    ]
