# Generated by Django 5.0.6 on 2024-07-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
