# Generated by Django 5.0.6 on 2024-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="video_thumbnails/"
            ),
        ),
    ]
