# Generated by Django 5.0.6 on 2024-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_program_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="program",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="program_picture/"
            ),
        ),
    ]
