# Generated by Django 5.0.6 on 2024-07-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0023_remove_program_thumbnail_program_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="picture",
        ),
    ]
