# Generated by Django 5.0.6 on 2024-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_remove_program_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
    ]
