# Generated by Django 5.0.6 on 2024-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_remove_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Bachelor", "Bachelor Degree"), ("Master", "Master Degree")],
                default="Bachelor",
                max_length=25,
                null=True,
            ),
        ),
    ]
