# Generated by Django 5.0.6 on 2024-07-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0027_program_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="course.program",
            ),
        ),
    ]
