# Generated by Django 5.0.6 on 2024-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0030_courseallocation_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseallocation",
            name="program",
            field=models.ManyToManyField(related_name="courses", to="course.program"),
        ),
    ]
