# Generated by Django 5.0.6 on 2024-07-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0031_alter_courseallocation_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="thumbnail",
        ),
    ]
