# Generated by Django 5.0.6 on 2024-07-11 19:13

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_progress_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="score",
            field=models.CharField(
                max_length=1024,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="Score",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("practice", "Practice Quiz"),
                ],
                max_length=50,
            ),
        ),
    ]
