# Generated by Django 5.0.6 on 2024-07-11 20:03

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_progress_options_alter_quiz_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progress",
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Записи прогресса пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Викторина", "verbose_name_plural": "Викторины"},
        ),
        migrations.AlterField(
            model_name="mcquestion",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Содержимое"),
                    ("random", "Случайный порядок"),
                    ("none", "Нет"),
                ],
                help_text="The order in which multichoice choice options are displayed to the user",
                max_length=30,
                null=True,
                verbose_name="Choice Order",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="score",
            field=models.CharField(
                max_length=1024,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="Счет",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="Правильный ответ НЕ показывается после вопроса. Ответы отображаются в конце.",
                verbose_name="Ответы в конце",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Задание"),
                    ("exam", "Экзамен"),
                    ("practice", "Практическое задание"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание викторины",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="draft",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Если да, викторина не отображается в списке викторин и может быть пройдена только пользователями, которые могут редактировать викторины.",
                verbose_name="Черновик",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="exam_paper",
            field=models.BooleanField(
                default=False,
                help_text="Если да, результат каждой попытки пользователя будет сохранен. Необходимо для оценки.",
                verbose_name="Экзаменационный лист",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="pass_mark",
            field=models.SmallIntegerField(
                blank=True,
                default=50,
                help_text="Процент, необходимый для прохождения экзамена.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Проходной балл",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="Показать вопросы в случайном порядке или как они установлены?",
                verbose_name="Случайный порядок",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="Если да, пользователю будет разрешена только одна попытка.",
                verbose_name="Одна попытка",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=60, verbose_name="Название"),
        ),
    ]
