# Generated by Django 5.0.6 on 2024-07-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_alter_question_figure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Выбор", "verbose_name_plural": "Выборы"},
        ),
        migrations.AlterModelOptions(
            name="essayquestion",
            options={
                "verbose_name": "Вопрос в стиле эссе",
                "verbose_name_plural": "Вопросы в стиле эссе",
            },
        ),
        migrations.AlterModelOptions(
            name="mcquestion",
            options={
                "verbose_name": "Вопрос с множественным выбором",
                "verbose_name_plural": "Вопросы с множественным выбором",
            },
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice",
            field=models.CharField(
                help_text="Введите выбранный текст, который вы хотите отобразить",
                max_length=1000,
                verbose_name="Контент",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="correct",
            field=models.BooleanField(
                default=False, help_text="Это правильный ответ?", verbose_name="Верно"
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.mcquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="mcquestion",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Содержимое"),
                    ("random", "Случайный порядок"),
                    ("none", "Нет"),
                ],
                help_text="Порядок, в котором пользователю отображаются параметры выбора с несколькими вариантами выбора",
                max_length=30,
                null=True,
                verbose_name="Порядок выбора",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.CharField(
                help_text="Введите текст вопроса, который вы хотите отобразить",
                max_length=1000,
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Объяснение будет приведено после того, как будет дан ответ на вопрос.",
                max_length=2000,
                verbose_name="Объяснение",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение к вопросу, если это необходимо.",
                null=True,
                upload_to="figure_pictures/",
                verbose_name="Изображение",
            ),
        ),
    ]
