# Generated by Django 5.0.6 on 2024-07-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_choice_options_alter_essayquestion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Тест", "verbose_name_plural": "Тесты"},
        ),
    ]
