# Generated by Django 5.0.6 on 2024-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_remove_student_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.URLField(blank=True, null=True),
        ),
    ]
