# Generated by Django 5.0.6 on 2024-07-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_facebook_user_instagram_user_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="facebook",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.URLField(blank=True, default="#", null=True),
        ),
    ]
