# Generated by Django 5.0.6 on 2024-07-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_facebook_alter_user_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("Bachloar", "Bachloar Degree"), ("Master", "Master Degree")],
                default="Bachloar",
                max_length=25,
            ),
        ),
    ]
