# Generated by Django 5.0.6 on 2024-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="facebook",
            field=models.URLField(
                blank=True, default="https://facebook.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.URLField(
                blank=True, default="'https://instagram.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.URLField(
                blank=True, default="https://web.telegram.org/k/#@soltanbkz", null=True
            ),
        ),
    ]
