# Generated by Django 5.0.6 on 2024-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_user_facebook_alter_user_instagram_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
    ]
