# Generated by Django 5.0.6 on 2024-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_remove_student_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("Bachloar", "Bachloar Degree"), ("Master", "Master Degree")],
                default="Bachloar",
                max_length=25,
                null=True,
            ),
        ),
    ]
