# Generated by Django 5.0.6 on 2024-07-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_student_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="telegram",
        ),
    ]
